---
title: "Seasonal hydrographs"
author: "Sam Bashevkin"
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  chunk_output_type: console
knit: (function(input, ...) {
    rmarkdown::render(
      input,
      output_dir = 'docs',
      knit_root_dir = "../",
      envir = globalenv()
    )
    })
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r, message=FALSE, warning=FALSE}
library(dplyr)
library(tidyr)
library(lubridate)
library(DroughtData)
library(ggplot2)
```

```{r}
d<-DroughtData::raw_hydro_1975_2021%>%
  mutate(Year=year(Date),
         WY=if_else(month(Date)>=10, Year+1, Year),
         doy=yday(Date),
         wdoy=case_when(
           leap_year(Year) & doy >=275 ~ doy -274,
           leap_year(Year) & doy <275 ~ doy + 92,
           !leap_year(Year) & doy >=274 ~ doy -273,
           !leap_year(Year) & doy <274 ~ doy + 92
         ))%>%
  left_join(DroughtData::lt_regional%>%
              distinct(YearAdj, SVIndex, YearType, Drought)%>%
              arrange(Drought, YearAdj)%>%
              group_by(Drought)%>%
              mutate(Lag=YearAdj-lag(YearAdj, order_by = YearAdj))%>%
              ungroup()%>%
              mutate(Start=if_else(is.na(Lag) | Lag>1, TRUE, FALSE),
                     Series_ID=1:n(),
                     Series_ID=if_else(Start, Series_ID, NA_integer_),
                     Series_ID=as.integer(as.factor(Series_ID)))%>%
              fill(Series_ID, .direction="down")%>%
              group_by(Series_ID)%>%
              arrange(YearAdj)%>%
              mutate(Series_year=1:n(),
                     Series_year2=if_else(Series_year>=3, "3+", as.character(Series_year)),
                     Series_year2=factor(Series_year2, levels=c("1", "2", "3+")))%>%
              select(-Lag, -Start),
            by=c("WY"="YearAdj"))%>%
  filter(!is.na(Drought))
```

Total inflow seasonal hydrograph by year
```{r}
ggplot(d, aes(x=doy, y=InflowTotal, color=Series_year2, group=WY))+
  geom_smooth(method="gam", formula=y~s(x, bs="cs", k=25))+
  facet_grid(Drought~., scales="free_y")+
  scale_color_viridis_d()+
  coord_cartesian(ylim=c(0, NA), expand = FALSE)+
  theme_bw()
```

Total inflow seasonal hydrograph by series_year
```{r}
ggplot(d, aes(x=wdoy, y=InflowTotal, color=Series_year2, group=Series_year2))+
  geom_smooth(method="gam", formula=y~s(x, bs="cs", k=25))+
  facet_grid(Drought~., scales="free_y")+
  scale_color_viridis_d()+
  coord_cartesian(ylim=c(0, NA), expand = FALSE)+
  theme_bw()
```
